TRUNCATE TABLE ejercicios_registro, ejercicios RESTART IDENTITY;

INSERT INTO ejercicios (nombre, met, categoria, tipo) VALUES
-- AEROBIC EXERCISES (100 total)
-- Running variations
('Correr (8 km/h)', 8.00, 'Cardio', 'AEROBICO'),
('Correr (10 km/h)', 10.00, 'Cardio', 'AEROBICO'),
('Correr (12 km/h)', 11.50, 'Cardio', 'AEROBICO'),
('Correr (15 km/h)', 14.00, 'Cardio', 'AEROBICO'),
('Correr en trail moderado', 9.80, 'Montaña', 'AEROBICO'),
-- Walking variations
('Caminar (5 km/h)', 3.50, 'Cardio', 'AEROBICO'),
('Caminar (6 km/h)', 4.00, 'Cardio', 'AEROBICO'),
('Caminata nórdica', 5.50, 'Cardio', 'AEROBICO'),
('Senderismo moderado', 6.30, 'Montaña', 'AEROBICO'),
('Cinta trotadora inclinada', 7.80, 'Cardio', 'AEROBICO'),
-- Cycling
('Ciclismo moderado (16-19 km/h)', 6.80, 'Ciclismo', 'AEROBICO'),
('Ciclismo rápido (20-22 km/h)', 8.90, 'Ciclismo', 'AEROBICO'),
('Ciclismo montaña moderado', 8.50, 'Ciclismo', 'AEROBICO'),
('Bicicleta estática moderada', 7.00, 'Ciclismo', 'AEROBICO'),
('Bicicleta estática intensa', 10.50, 'Ciclismo', 'AEROBICO'),
-- Swimming
('Natación (crawl moderado)', 8.00, 'Agua', 'AEROBICO'),
('Natación (crawl rápido)', 11.00, 'Agua', 'AEROBICO'),
('Natación estilo pecho', 7.40, 'Agua', 'AEROBICO'),
('Natación estilo espalda', 7.00, 'Agua', 'AEROBICO'),
('Natación mariposa', 13.60, 'Agua', 'AEROBICO'),
('Aeróbica acuática', 4.50, 'Agua', 'AEROBICO'),
-- Rowing and elliptical
('Máquina de remo moderada', 7.00, 'Cardio', 'AEROBICO'),
('Máquina de remo intensa', 12.00, 'Cardio', 'AEROBICO'),
('Máquina elíptica moderada', 6.50, 'Cardio', 'AEROBICO'),
('Máquina elíptica intensa', 9.80, 'Cardio', 'AEROBICO'),
-- Jumping and climbing
('Saltar a la cuerda moderado', 10.00, 'Cardio', 'AEROBICO'),
('Saltar a la cuerda rápido', 12.30, 'Cardio', 'AEROBICO'),
('Subida de escaleras', 9.00, 'Cardio', 'AEROBICO'),
('Escaladora de máquina', 8.50, 'Cardio', 'AEROBICO'),
-- Dance and aerobics
('Aeróbica (bajo impacto)', 5.00, 'Baile', 'AEROBICO'),
('Aeróbica (alto impacto)', 8.00, 'Baile', 'AEROBICO'),
('Zumba', 7.50, 'Baile', 'AEROBICO'),
('Salsa', 6.80, 'Baile', 'AEROBICO'),
('Flamenco', 5.80, 'Baile', 'AEROBICO'),
('Hip-hop', 6.00, 'Baile', 'AEROBICO'),
('Danza contemporánea', 6.50, 'Baile', 'AEROBICO'),
('Step aeróbico', 8.00, 'Baile', 'AEROBICO'),
-- Combat sports
('Kickboxing', 10.30, 'Combate', 'AEROBICO'),
('Boxeo', 12.00, 'Combate', 'AEROBICO'),
('Artes marciales', 9.80, 'Combate', 'AEROBICO'),
('Judo', 10.30, 'Combate', 'AEROBICO'),
('Tai Chi', 4.00, 'Combate', 'AEROBICO'),
-- Mind-body and fitness
('Yoga vigoroso', 5.00, 'Yoga', 'AEROBICO'),
('Pilates', 4.50, 'Yoga', 'AEROBICO'),
-- Ball sports
('Baloncesto', 8.00, 'Deporte', 'AEROBICO'),
('Fútbol/Futsal', 9.50, 'Deporte', 'AEROBICO'),
('Voleibol', 4.00, 'Deporte', 'AEROBICO'),
('Tenis', 8.00, 'Raqueta', 'AEROBICO'),
('Pádel', 7.30, 'Raqueta', 'AEROBICO'),
('Squash', 9.00, 'Raqueta', 'AEROBICO'),
('Bádminton', 5.50, 'Raqueta', 'AEROBICO'),
('Balonmano', 8.00, 'Deporte', 'AEROBICO'),
('Waterpolo', 10.00, 'Agua', 'AEROBICO'),
-- Water sports
('Kayak moderado', 5.80, 'Agua', 'AEROBICO'),
('Kayak rápido', 8.00, 'Agua', 'AEROBICO'),
('Surf', 7.50, 'Agua', 'AEROBICO'),
-- Board sports
('Skateboarding', 6.00, 'Deporte', 'AEROBICO'),
('Patinaje sobre ruedas', 6.50, 'Deporte', 'AEROBICO'),
-- Winter sports
('Esquí moderado', 7.00, 'Montaña', 'AEROBICO'),
('Snowboarding', 7.50, 'Montaña', 'AEROBICO'),
-- Climbing
('Escalada en pared (moderada)', 8.00, 'Montaña', 'AEROBICO'),
('Escalada en pared (intensa)', 10.00, 'Montaña', 'AEROBICO'),
-- Cross-training and circuits
('Entrenamiento cruzado', 7.50, 'Cardio', 'AEROBICO'),
('Entrenamiento en circuito', 8.00, 'Cardio', 'AEROBICO'),
('HIIT (entrenamiento de alta intensidad)', 12.50, 'Cardio', 'AEROBICO'),
('Saltos caseros (sostenido)', 8.00, 'Cardio', 'AEROBICO'),
('Burpees (sostenido)', 8.00, 'Cardio', 'AEROBICO'),
('Mountain climbers (sostenido)', 8.00, 'Cardio', 'AEROBICO'),
('Spinning', 9.00, 'Ciclismo', 'AEROBICO'),
('Trampolín', 5.00, 'Cardio', 'AEROBICO'),
('Frisbee (movimiento activo)', 4.00, 'Deporte', 'AEROBICO'),
('Tiro con arco (caminando)', 4.50, 'Deporte', 'AEROBICO'),
('Golf (caminando)', 4.50, 'Deporte', 'AEROBICO'),
-- Additional aerobic exercises to reach 100 total
('Corredor de escaleras dinámico', 10.50, 'Cardio', 'AEROBICO'),
('Bicicleta de montaña (subida)', 9.80, 'Ciclismo', 'AEROBICO'),
('Natación con tablas', 5.50, 'Agua', 'AEROBICO'),
('Entrenamiento de boxeo (bolsa)', 9.50, 'Combate', 'AEROBICO'),
('Calistenia (movimiento rápido)', 7.50, 'Cardio', 'AEROBICO'),
('Bailoterapia', 6.50, 'Baile', 'AEROBICO'),
('Escalada rápida en pared', 11.00, 'Montaña', 'AEROBICO'),
('Ciclismo en pista velodrómica', 11.00, 'Ciclismo', 'AEROBICO'),
('Carrera de velocidad (sprint)', 15.00, 'Cardio', 'AEROBICO'),
('Salto de longitud (repetido)', 8.00, 'Deporte', 'AEROBICO'),
('Slackline (activo)', 5.50, 'Deporte', 'AEROBICO'),
('Treking intenso en montaña', 8.50, 'Montaña', 'AEROBICO'),
('Natación de competición (largo)', 12.00, 'Agua', 'AEROBICO'),
('Saltos repetidos (continuo)', 9.00, 'Cardio', 'AEROBICO'),
('Bicicleta de piñón fijo', 8.00, 'Ciclismo', 'AEROBICO'),
('Marcha atlética rápida', 5.80, 'Cardio', 'AEROBICO'),
('Boxeo de entrenamiento completo', 11.50, 'Combate', 'AEROBICO'),
('Parkour', 10.00, 'Deporte', 'AEROBICO'),
('Marcha nórdica rápida', 6.50, 'Cardio', 'AEROBICO'),
('Fútbol de sala intenso', 10.00, 'Deporte', 'AEROBICO'),
('Rugby', 10.50, 'Deporte', 'AEROBICO'),
('Hockey sobre hielo', 10.00, 'Deporte', 'AEROBICO'),
('Lacrosse', 9.50, 'Deporte', 'AEROBICO'),
('Cricket (activo)', 7.00, 'Deporte', 'AEROBICO'),
('Sófbol/Béisbol', 6.50, 'Deporte', 'AEROBICO'),
('Salto de trampolín acrobático', 8.50, 'Deporte', 'AEROBICO'),
('Aeróbica acuática dinámica', 6.50, 'Agua', 'AEROBICO'),

-- ANAEROBIC EXERCISES (100 total, 25 per intensity)
-- CALENTAMIENTO (met=3.0)
('Movilidad articular hombros', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Movilidad articular caderas', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Rotaciones cervicales', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Círculos de brazos', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Estiramiento cuádriceps de pie', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Estiramiento isquiotibiales de pie', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Estiramiento de gemelos', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Caminata lenta en cinta', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Marcha en el sitio', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Rotación de tobillos', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Rotación de muñecas', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Elevación de rodillas lenta', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Glúteo kickback sin peso', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Abducción lateral pierna sin peso', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Rotación de cadera cuadrupedia', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Extensión de columna en suelo', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Apertura pectoral con brazos', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Balanceo lateral de piernas', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Flexión lateral de tronco', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Movilidad escapular', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Círculos de caderas', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Puente de glúteos sin peso', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Plancha de rodillas', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Zancada lateral lenta', 3.0, 'Calentamiento', 'ANAEROBICO'),
('Marcha con elevación de talones', 3.0, 'Calentamiento', 'ANAEROBICO'),

-- ALTA REPETICIÓN (met=5.0)
('Sentadilla con peso corporal', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Flexiones rodillas', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Zancadas sin peso', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Fondos en silla', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Elevación de talones de pie', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Remo con banda elástica', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Press banca con mancuernas ligeras', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Curl bíceps con banda elástica', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Extensión tríceps con banda', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Patada trasera con banda', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Abducción de cadera con banda', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Aducción de cadera con banda', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Elevación lateral con mancuerna ligera', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Press militar con mancuerna ligera', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Superman en suelo', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Bird-Dog', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Plancha lateral corta', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Crunch abdominal', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Elevación de piernas en suelo', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Tijeras abdominales', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Remo con mancuerna ligera', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Peso muerto rumano con mancuerna ligera', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Step-up sin peso', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Glúteo donkey kick con banda', 5.0, 'Alta repetición', 'ANAEROBICO'),
('Rotación rusa con peso ligero', 5.0, 'Alta repetición', 'ANAEROBICO'),

-- MODERADA INTENSIDAD (met=8.0)
('Sentadilla con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Press banca con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Peso muerto', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Remo con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Press militar con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Dominadas asistidas', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Fondos en paralelas', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Curl bíceps con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Press inclinado con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Remo con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Extensión de piernas en máquina', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Curl femoral en máquina', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Press de pierna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Jalón al pecho', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Remo en máquina', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Hip thrust con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Sentadilla búlgara', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Zancada con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Press Arnold', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Face pull con cable', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Aperturas pectoral con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Extensión tríceps con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Curl martillo', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Elevación lateral con mancuerna', 8.0, 'Moderada intensidad', 'ANAEROBICO'),
('Encogimiento de hombros con barra', 8.0, 'Moderada intensidad', 'ANAEROBICO'),

-- ALTA INTENSIDAD (met=12.0)
('Sentadilla trasera pesada', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Press banca pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Peso muerto máximo', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Sentadilla frontal', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Clean and press', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Snatch con barra', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Thruster', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Dominadas con lastre', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Fondos con lastre', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Sprint en cinta', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Box jump', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Salto al cajón', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Power clean', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Push press', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Sentadilla olímpica', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Peso muerto sumo pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Press inclinado pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Remo Pendlay', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Press militar de pie pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Jump squat con peso', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Sentadilla hack', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Déficit deadlift', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Kettlebell swing pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Battle rope pesado', 12.0, 'Alta intensidad', 'ANAEROBICO'),
('Tire flip', 12.0, 'Alta intensidad', 'ANAEROBICO');
