-- Añade intensidad y num_series al registro de ejercicio (para ejercicios anaeróbicos)
ALTER TABLE ejercicios_registro ADD COLUMN IF NOT EXISTS intensidad VARCHAR(10) NULL;
ALTER TABLE ejercicios_registro ADD COLUMN IF NOT EXISTS num_series  SMALLINT    NULL;

-- Elimina el seed de V19 (ejercicios anaeróbicos con intensidad bakeada en MET/categoría)
DELETE FROM ejercicios WHERE tipo = 'ANAEROBICO';

-- 100 ejercicios anaeróbicos limpios (el usuario elige intensidad al registrar)
INSERT INTO ejercicios (nombre, met, categoria, tipo) VALUES
-- PECHO
('Press banca con barra',            8.0, 'Pecho',    'ANAEROBICO'),
('Press banca inclinado',            7.5, 'Pecho',    'ANAEROBICO'),
('Press banca declinado',            7.5, 'Pecho',    'ANAEROBICO'),
('Press de pecho máquina',           6.0, 'Pecho',    'ANAEROBICO'),
('Aperturas con mancuernas',         5.0, 'Pecho',    'ANAEROBICO'),
('Fondos en paralelas',              7.0, 'Pecho',    'ANAEROBICO'),
('Flexiones',                        6.0, 'Pecho',    'ANAEROBICO'),
('Flexiones diamante',               6.5, 'Pecho',    'ANAEROBICO'),
('Cruces con cable',                 5.0, 'Pecho',    'ANAEROBICO'),
('Pullover con mancuerna',           5.5, 'Pecho',    'ANAEROBICO'),
-- ESPALDA
('Dominadas',                        9.0, 'Espalda',  'ANAEROBICO'),
('Jalón al pecho',                   7.0, 'Espalda',  'ANAEROBICO'),
('Jalón trasnuca',                   7.0, 'Espalda',  'ANAEROBICO'),
('Remo con barra',                   8.0, 'Espalda',  'ANAEROBICO'),
('Remo con mancuerna',               7.0, 'Espalda',  'ANAEROBICO'),
('Peso muerto convencional',         8.0, 'Espalda',  'ANAEROBICO'),
('Peso muerto rumano',               7.5, 'Espalda',  'ANAEROBICO'),
('Remo en polea baja',               6.5, 'Espalda',  'ANAEROBICO'),
('Hiperextensiones de espalda',      4.5, 'Espalda',  'ANAEROBICO'),
('Encogimientos de hombros barra',   5.0, 'Espalda',  'ANAEROBICO'),
('Face pull con cable',              4.5, 'Espalda',  'ANAEROBICO'),
('Remo en máquina',                  6.5, 'Espalda',  'ANAEROBICO'),
-- HOMBROS
('Press militar con barra',          7.0, 'Hombros',  'ANAEROBICO'),
('Press Arnold',                     6.5, 'Hombros',  'ANAEROBICO'),
('Elevaciones laterales',            4.0, 'Hombros',  'ANAEROBICO'),
('Elevaciones frontales',            4.0, 'Hombros',  'ANAEROBICO'),
('Elevaciones posteriores',          4.0, 'Hombros',  'ANAEROBICO'),
('Press de hombros máquina',         6.0, 'Hombros',  'ANAEROBICO'),
('Encogimientos con mancuernas',     4.5, 'Hombros',  'ANAEROBICO'),
('Push press',                       9.0, 'Hombros',  'ANAEROBICO'),
-- BÍCEPS
('Curl bíceps con barra',            5.0, 'Bíceps',   'ANAEROBICO'),
('Curl bíceps alterno mancuerna',    5.0, 'Bíceps',   'ANAEROBICO'),
('Curl martillo',                    4.5, 'Bíceps',   'ANAEROBICO'),
('Curl concentrado',                 4.0, 'Bíceps',   'ANAEROBICO'),
('Curl en polea baja',               4.5, 'Bíceps',   'ANAEROBICO'),
('Curl predicador',                  4.5, 'Bíceps',   'ANAEROBICO'),
('Curl 21s',                         5.0, 'Bíceps',   'ANAEROBICO'),
('Curl en máquina',                  4.5, 'Bíceps',   'ANAEROBICO'),
-- TRÍCEPS
('Extensiones de tríceps en polea',  5.0, 'Tríceps',  'ANAEROBICO'),
('Press francés barra Z',            5.5, 'Tríceps',  'ANAEROBICO'),
('Fondos de tríceps en banco',       5.5, 'Tríceps',  'ANAEROBICO'),
('Patada de tríceps',                4.0, 'Tríceps',  'ANAEROBICO'),
('Extensiones sobre la cabeza',      5.0, 'Tríceps',  'ANAEROBICO'),
('Press cerrado con barra',          7.0, 'Tríceps',  'ANAEROBICO'),
('Extensiones de tríceps máquina',   4.5, 'Tríceps',  'ANAEROBICO'),
('Kickback de tríceps',              4.0, 'Tríceps',  'ANAEROBICO'),
-- PIERNAS
('Sentadilla con barra',             8.0, 'Piernas',  'ANAEROBICO'),
('Sentadilla frontal',               8.0, 'Piernas',  'ANAEROBICO'),
('Sentadilla sumo',                  7.5, 'Piernas',  'ANAEROBICO'),
('Sentadilla búlgara',               7.5, 'Piernas',  'ANAEROBICO'),
('Sentadilla hack',                  7.5, 'Piernas',  'ANAEROBICO'),
('Prensa de piernas',                7.0, 'Piernas',  'ANAEROBICO'),
('Extensiones de cuádriceps',        5.0, 'Piernas',  'ANAEROBICO'),
('Curl femoral tumbado',             5.0, 'Piernas',  'ANAEROBICO'),
('Curl femoral de pie',              5.0, 'Piernas',  'ANAEROBICO'),
('Hip thrust con barra',             7.0, 'Piernas',  'ANAEROBICO'),
('Peso muerto sumo',                 8.0, 'Piernas',  'ANAEROBICO'),
('Zancadas con mancuernas',          6.5, 'Piernas',  'ANAEROBICO'),
('Zancadas caminando',               6.5, 'Piernas',  'ANAEROBICO'),
('Gemelos de pie',                   4.5, 'Piernas',  'ANAEROBICO'),
('Gemelos sentado',                  4.5, 'Piernas',  'ANAEROBICO'),
('Step-up con mancuernas',           6.0, 'Piernas',  'ANAEROBICO'),
('Abductores en máquina',            4.0, 'Piernas',  'ANAEROBICO'),
('Adductores en máquina',            4.0, 'Piernas',  'ANAEROBICO'),
-- CORE
('Plancha abdominal',                4.0, 'Core',     'ANAEROBICO'),
('Plancha lateral',                  3.8, 'Core',     'ANAEROBICO'),
('Crunch abdominal',                 4.0, 'Core',     'ANAEROBICO'),
('Crunch inclinado',                 4.5, 'Core',     'ANAEROBICO'),
('Elevación de piernas colgado',     5.0, 'Core',     'ANAEROBICO'),
('Russian twist',                    4.5, 'Core',     'ANAEROBICO'),
('Rueda abdominal',                  5.5, 'Core',     'ANAEROBICO'),
('Superman',                         3.5, 'Core',     'ANAEROBICO'),
('Bird-dog',                         3.5, 'Core',     'ANAEROBICO'),
('Oblicuos con polea',               4.5, 'Core',     'ANAEROBICO'),
('Tijeras abdominales',              4.0, 'Core',     'ANAEROBICO'),
('Crunch en máquina',                4.5, 'Core',     'ANAEROBICO'),
-- FUNCIONAL / OLÍMPICO
('Clean and press',                 11.0, 'Olímpico', 'ANAEROBICO'),
('Snatch con barra',                12.0, 'Olímpico', 'ANAEROBICO'),
('Power clean',                     10.0, 'Olímpico', 'ANAEROBICO'),
('Thruster',                        10.0, 'Olímpico', 'ANAEROBICO'),
('Turkish get-up',                   8.0, 'Olímpico', 'ANAEROBICO'),
('Kettlebell swing',                 9.0, 'Olímpico', 'ANAEROBICO'),
('Kettlebell goblet squat',          7.0, 'Olímpico', 'ANAEROBICO'),
('Box jump',                        10.0, 'Olímpico', 'ANAEROBICO'),
('Saltos al step',                   8.0, 'Olímpico', 'ANAEROBICO'),
('Battle ropes',                    10.0, 'Olímpico', 'ANAEROBICO'),
('Sled push',                        9.0, 'Olímpico', 'ANAEROBICO'),
('Muscle-up',                       11.0, 'Olímpico', 'ANAEROBICO'),
-- ADICIONALES
('Buenos días con barra',            7.0, 'Espalda',  'ANAEROBICO'),
('Press inclinado con mancuernas',   7.0, 'Pecho',    'ANAEROBICO'),
('Remo con barra T',                 7.5, 'Espalda',  'ANAEROBICO'),
('Déficit deadlift',                 8.5, 'Espalda',  'ANAEROBICO'),
('Rack pull',                        8.0, 'Espalda',  'ANAEROBICO'),
('Sentadilla overhead',              8.0, 'Piernas',  'ANAEROBICO'),
('Sissy squat',                      6.0, 'Piernas',  'ANAEROBICO'),
('Zancada reversa',                  6.5, 'Piernas',  'ANAEROBICO'),
('Peso muerto a una pierna',         7.0, 'Piernas',  'ANAEROBICO'),
('Press de hombros unilateral',      6.0, 'Hombros',  'ANAEROBICO'),
('Curl femoral nórdico',             7.0, 'Piernas',  'ANAEROBICO'),
('Hip thrust a una pierna',          6.5, 'Piernas',  'ANAEROBICO');
